# Generated by Django 2.0.7 on 2018-07-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateTimeField()),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('total_mark', models.IntegerField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teacher')),
            ],
        ),
    ]
