# Generated by Django 2.0.7 on 2018-07-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_pass', models.CharField(max_length=200)),
                ('teacher_cpass', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('img', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
