# Generated by Django 2.0.7 on 2018-07-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180725_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.IntegerField(),
        ),
    ]
