# Generated by Django 2.0.7 on 2018-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='obtain_mark',
            field=models.IntegerField(default=0),
        ),
    ]
