# Generated by Django 2.0.7 on 2018-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180726_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='obtain_mark',
            field=models.IntegerField(default=None),
        ),
    ]
